
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSDIVIDE EQUALS LPAREN MINUS NAME NUMBER PLUS RPAREN TIMESstatement : NAME EQUALS expressionstatement : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBER'
    
_lr_action_items = {'NAME':([0,],[2,]),'MINUS':([0,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,],[4,9,4,4,-9,4,4,4,4,4,-7,9,9,-3,-4,-5,-6,-8,]),'LPAREN':([0,4,5,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'$end':([1,3,6,12,14,15,16,17,18,19,],[0,-2,-9,-7,-1,-3,-4,-5,-6,-8,]),'EQUALS':([2,],[7,]),'PLUS':([3,6,12,13,14,15,16,17,18,19,],[8,-9,-7,8,8,-3,-4,-5,-6,-8,]),'TIMES':([3,6,12,13,14,15,16,17,18,19,],[10,-9,-7,10,10,10,10,-5,-6,-8,]),'DIVIDE':([3,6,12,13,14,15,16,17,18,19,],[11,-9,-7,11,11,11,11,-5,-6,-8,]),'RPAREN':([6,12,13,15,16,17,18,19,],[-9,-7,19,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,7,8,9,10,11,],[3,12,13,14,15,16,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','calculator.py',67),
  ('statement -> expression','statement',1,'p_statement_expr','calculator.py',72),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','calculator.py',77),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','calculator.py',78),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','calculator.py',79),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','calculator.py',80),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','calculator.py',92),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calculator.py',97),
  ('expression -> NUMBER','expression',1,'p_expression_number','calculator.py',102),
]
